#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
python3 scripts/check-tools.py

# Non-interactive shells (CI, direct invocation) may not have cargo/pnpm on PATH.
# Source the standard rustup env file if present; tolerate absence so that
# environments already configured (GitHub Actions setup steps, dev shells) work
# unchanged.
if [[ -f "$HOME/.cargo/env" ]]; then
  # shellcheck disable=SC1091
  source "$HOME/.cargo/env"
fi

PROTO_DIR="packages/contracts/proto"
RUST_CRATE="packages/contracts/crates/rust"
TS_PKG="packages/contracts/ts/contracts"

echo "==> Rust: regenerate popclaw-contracts via build.rs"
# Force build.rs to re-run by touching a proto file marker
touch "$PROTO_DIR/identity.proto"
cargo build --locked -p popclaw-contracts >/dev/null

echo "==> TypeScript: regenerate @popclaw/contracts via pbjs+pbts"
mkdir -p "$TS_PKG/src/generated"
TS_OUT_JS="$TS_PKG/src/generated/index.js"
TS_OUT_DTS="$TS_PKG/src/generated/index.d.ts"

# Invoke protobufjs-cli from the workspace root (root devDep).
# Deliberate flags:
#   -t static-module   — emit a single ES module with classes + encode/decode
#   -w es6             — ES module wrapper
#   --no-verify        — skip verify methods (we validate on the Rust side)
#   --no-delimited     — skip delimited encoding helpers
# protobufjs uses its installed Long runtime for decoded int64/uint64 values.
# Keep Long values intact; never coerce counters above 2^53-1 to JS Number.
# The wide-integer and presence fixtures verify the resolved runtime behavior.
pnpm exec pbjs \
  -t static-module -w es6 \
  --no-verify --no-delimited \
  -o "$TS_OUT_JS" \
  "$PROTO_DIR/identity.proto" \
  "$PROTO_DIR/event.proto" \
  "$PROTO_DIR/invite.proto" \
  "$PROTO_DIR/quest.proto" \
  "$PROTO_DIR/profile.proto" \
  "$PROTO_DIR/house_session.proto" \
  "$PROTO_DIR/world_interaction.proto" \
  "$PROTO_DIR/public_stream.proto"

pnpm exec pbts -o "$TS_OUT_DTS" "$TS_OUT_JS"

# Also emit the reflection descriptor as an ES module (`-t json-module`).
# The static-module output above is plain classes with NO reflection metadata,
# so it cannot answer "does this field track explicit presence?". The
# canonicalizer needs exactly that: proto3 `optional` fields (explicit presence)
# MUST emit even when empty, while implicit-presence scalars MUST elide. Driving
# that off the schema keeps it correct as the schema changes, instead of a
# hand-maintained field list that silently rots.
#
# Emitted as PURE DATA (`-t json` wrapped in `export default`) rather than
# `-t json-module`, which would emit `import ... from "protobufjs/light"` — a
# bare specifier Node's native ESM resolver rejects (the same class of breakage
# the static-module sed below works around).
TS_OUT_DESC="$TS_PKG/src/generated/descriptor.js"
{
  echo "// GENERATED by scripts/gen-proto.sh — do not edit."
  echo "// protobuf reflection descriptor; consumed via protobufjs Root.fromJSON."
  printf 'export default '
} > "$TS_OUT_DESC"
pnpm exec pbjs \
  -t json \
  "$PROTO_DIR/identity.proto" \
  "$PROTO_DIR/event.proto" \
  "$PROTO_DIR/invite.proto" \
  "$PROTO_DIR/quest.proto" \
  "$PROTO_DIR/profile.proto" \
  "$PROTO_DIR/house_session.proto" \
  "$PROTO_DIR/world_interaction.proto" \
  "$PROTO_DIR/public_stream.proto" >> "$TS_OUT_DESC"
echo ";" >> "$TS_OUT_DESC"

# Post-process: pbjs emits `import * as $protobuf from "protobufjs/minimal"`,
# which works under esbuild/vitest bundler interop but fails at runtime in
# Node's native ESM (where `import * as` over a CJS module only surfaces
# { default }, dropping named exports like Reader/Writer/util/roots).
# Swap to a default import which receives the full CJS module.exports.
# Idempotent: re-running the substitution is a no-op once done.
if grep -q 'import \* as \$protobuf from "protobufjs/minimal";' "$TS_OUT_JS"; then
  # BSD sed (macOS) needs -i '' — portable variant uses a backup suffix + rm.
  sed -i.bak 's|import \* as \$protobuf from "protobufjs/minimal";|import $protobuf from "protobufjs/minimal";|' "$TS_OUT_JS"
  rm -f "$TS_OUT_JS.bak"
fi

echo "==> Done. Generated files written to:"
echo "    $RUST_CRATE/src/generated/"
echo "    $TS_PKG/src/generated/"

python3 scripts/postprocess-ts.py
# The descriptor is the fixed Python consumption input and Rust wire schema.
protoc -I "$PROTO_DIR" --descriptor_set_out="$PROTO_DIR/descriptor.pb" --include_imports "$PROTO_DIR"/*.proto
