/**
 * The **disk-facing side** of DM attachments — read the local file in before
 * sending, write the decoded bytes down after receiving.
 * Encryption itself lives in `dm-crypto.ts` (it only moves bytes and doesn't
 * know about formats); this file only handles bytes, type, and file name.
 *
 * Why both ends live in this one file: the mime table has to be used
 * bidirectionally (send: extension → mime; receive: mime → extension), and
 * splitting it into two places would inevitably get out of sync one day.
 *
 * **What the whitelist accepts, and why not "accept anything"**:
 *  - Images: already supported.
 *  - Voice: ordinary person-to-person voice clips.
 *  - Text an agent can read (md/txt/csv/json): popclaw is an AI social
 *    network, and "send a spec to the other party's agent so it can follow
 *    it" is a use case ordinary IM doesn't have. The file name alone is
 *    already a statement.
 *  - **zip / executables are not accepted**: the recipient cannot read them
 *    without unpacking or running them. Capacity does not change this allowlist.
 *
 * No magic-number sniffing. What sniffing would guard against is "the owner
 * renamed a .txt to .png" — and that person is the owner themself. Unsupported
 * formats are blocked by extension; capacity is checked on the signed envelope.
 *
 * **`EXT_BY_MIME` must stay a fixed table**: the mime is written into the box
 * by the **sender**, and if the on-disk extension followed it, the sender
 * could decide whether this file is called `.sh` or `.md` on your disk.
 * Unrecognized mimes are always saved as `.bin`. The same applies to the
 * on-disk name — it is always generated by us (`<ts>-<first 8 chars of
 * sender id>.<ext>`).
 */
import { readFileSync, mkdirSync, writeFileSync, realpathSync, linkSync, unlinkSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { timeContext } from '../time/time-context.js';
import { deriveSigil } from '../invite/sigil.js';
import { join, relative, isAbsolute, extname } from 'node:path';
import type { popclaw } from '@popclaw/contracts';
import type { Signer } from '../identity/signer.js';
import { readDmMedia } from './dm-plaintext.js';
import { renderCopy } from '../lexicon/index.js';
import { ownerLang } from '../lexicon/owner-language.js';

/** Formats allowed to be sent as attachments. Unrecognized extensions are always
 *  rejected — never guess (see the file header for why). */
const MIME_BY_EXT: Record<string, string> = {
  // images
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  gif: 'image/gif',
  webp: 'image/webp',
  // voice (Telegram voice clips are ogg/opus; WeChat/Feishu are mostly m4a or mp3)
  ogg: 'audio/ogg',
  oga: 'audio/ogg',
  opus: 'audio/ogg',
  m4a: 'audio/mp4',
  mp3: 'audio/mpeg',
  wav: 'audio/wav',
  amr: 'audio/amr',
  // text an agent can read
  md: 'text/markdown',
  txt: 'text/plain',
  csv: 'text/csv',
  json: 'application/json',
  pdf: 'application/pdf',
};

const EXT_BY_MIME: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/gif': 'gif',
  'image/webp': 'webp',
  'audio/ogg': 'ogg',
  'audio/mp4': 'm4a',
  'audio/mpeg': 'mp3',
  'audio/wav': 'wav',
  'audio/amr': 'amr',
  'text/markdown': 'md',
  'text/plain': 'txt',
  'text/csv': 'csv',
  'application/json': 'json',
  'application/pdf': 'pdf',
};

/** The attachment's broad category — only used to pick the right natural-language
 *  unit (an image / a voice clip / a file). */
export type DmAttachmentKind = 'image' | 'audio' | 'doc';

/** Determine the broad category from a mime or local path; anything unrecognized
 *  is treated as doc. */
export function attachmentKind(mimeOrPath: string): DmAttachmentKind {
  const v = mimeOrPath.trim().toLowerCase();
  // Don't use `includes('/')` to detect mime — **a path also contains slashes**,
  // which would make every image get misjudged as a doc (caught immediately by
  // the unit tests). A mime must look like `type/subtype` as a whole.
  const mime = /^[a-z]+\/[a-z0-9.+-]+$/.test(v) ? v : (MIME_BY_EXT[v.split('.').pop() ?? ''] ?? '');
  if (mime.startsWith('image/')) return 'image';
  if (mime.startsWith('audio/')) return 'audio';
  return 'doc';
}

export type LoadedDmAttachment =
  | { ok: true; bytes: Uint8Array; mime: string; name: string }
  /** `text` is already owner-facing natural language (with concrete numbers and
   *  next steps); the caller can echo it back as-is. */
  | { ok: false; text: string };

/**
 * Read the original bytes and validate the format. At draft time, additionally
 * checkDirectMessageFits with the actual recipient, body and attachment.
 * Neither step makes a network call or modifies the source file.
 */
export function loadDmAttachment(path: string): LoadedDmAttachment {
  const lang = ownerLang();
  const name = path.split(/[/\\]/).pop() || path;
  const ext = name.includes('.') ? name.split('.').pop()!.toLowerCase() : '';
  const mime = MIME_BY_EXT[ext];
  if (!mime) {
    return { ok: false, text: renderCopy(lang, 'dm.attachment.badFormat', { name }) };
  }
  let buf: Buffer;
  try {
    buf = readFileSync(path);
  } catch {
    return { ok: false, text: renderCopy(lang, 'dm.attachment.notFound', { path }) };
  }
  if (buf.byteLength === 0) return { ok: false, text: renderCopy(lang, 'dm.attachment.empty', { name }) };
  return { ok: true, bytes: new Uint8Array(buf), mime, name };
}

/** `123456 → "120.6 KB"` — the concrete number in the honest copy. */
export function kb(bytes: number): string {
  return `${(bytes / 1024).toFixed(1)} KB`;
}

/**
 * Nickname sanitization — **a sender's self-reported nickname must never go into
 * a path as-is**.
 *
 * Only CJK characters / letters / digits / `-` / `_` are kept; everything else
 * is dropped, and the result is truncated to 16 characters. This way
 * `../../evil`, `a/b`, a thousand-character name, or RTL-override characters
 * all land as a safe short string; if sanitization leaves nothing (a nickname
 * that's pure symbols or emoji), it returns `''` and the caller falls back to
 * the sigil alone.
 */
function safeNamePart(nickname: string): string {
  return [...nickname.normalize('NFC')]
    .filter((ch) => /[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}\p{L}\p{N}_-]/u.test(ch))
    .join('')
    .slice(0, 16);
}

/**
 * On-disk file name: `<owner-local date>_<hour+minute>_<nickname>-<sigil>.<ext>`,
 * e.g. `2026-07-31_1507_host-c-9b2y5d3f.ogg`.
 *
 * The owner's own words (2026-07-31): a "string of digits and letters" like
 * `1785481431-5E7DAm6B.ogg` reads terribly — once you have several, they get
 * confused. We have three pieces of material available, each with its own role:
 *  - **Time** uses the owner's local date and hour+minute (`timeContext`,
 *    ADR-0045), not unix seconds — `1785481431` is pure noise to a human; with
 *    date first, files sort by time naturally in a folder.
 *  - **Nickname** is the entire source of readability, but it is
 *    **self-reported by the sender**, so it must go through `safeNamePart` first.
 *  - **Sigil** is derived from the id and **cannot be forged**, so it's the
 *    fallback: if the nickname sanitizes to empty, only the sigil is kept,
 *    falling back to today's readability without getting any worse; it also
 *    disambiguates duplicate/impersonated nicknames.
 *
 * **Never use the raw file name the sender supplied** (which today's protocol
 * doesn't even transmit): that would be the front door to path traversal.
 *
 * This is the readable prefix. saveDmMedia appends the full content hash
 * and publishes complete bytes atomically, so same-minute images cannot collide.
 */
export function dmMediaFileName(
  ts: number,
  fromPopclawId: string,
  ext: string,
  deps: { sigilOf: (id: string) => string; nameOf?: (id: string) => string },
): string {
  const t = timeContext(ts);
  const stamp = `${t.ymd}_${t.hm.replace(':', '')}`;
  const who = safeNamePart(deps.nameOf?.(fromPopclawId) ?? '');
  const sigil = deps.sigilOf(fromPopclawId);
  return `${stamp}_${who ? `${who}-` : ''}${sigil}.${ext}`;
}

/**
 * Save the received image to `data/dm-media/` (a disposable layer: the
 * ciphertext still sits on the lore-house and can be re-fetched).
 *
 * See `dmMediaFileName` for the file name (readability-first, time+sigil as
 * fallback), followed by the full content hash. Replay reuses identical bytes;
 * a complete temporary file is linked atomically so concurrent hosts never
 * observe a partially written attachment.
 *
 * Returns null on failure and **never throws**: a single image failing to write
 * should not block text delivery (the inbound loop has a track record of 3x/9x
 * duplicate delivery, so any new throw point is a hazard).
 */
export function saveDmMedia(
  dir: string,
  dm: { ts: number; fromPopclawId: string },
  media: { mime: string; bytes: Uint8Array },
  onError?: (err: unknown) => void,
  /** The two local sources used for naming. Omit = sigil only (the name is still
   *  readable, just without a nickname). */
  naming: { sigilOf: (id: string) => string; nameOf?: (id: string) => string } = { sigilOf: deriveSigil },
): string | null {
  try {
    const ext = EXT_BY_MIME[media.mime] ?? 'bin';
    mkdirSync(dir, { recursive: true });
    const readable = dmMediaFileName(dm.ts, dm.fromPopclawId || '', ext, naming);
    const digest = createHash('sha256').update(media.bytes).digest('hex');
    const path = join(dir, `${readable.slice(0, -(ext.length + 1))}-${digest}.${ext}`);
    const staging = join(dir, `.incoming-${randomUUID()}`);
    try {
      writeFileSync(staging, media.bytes, { flag: 'wx', mode: 0o600 });
      try { linkSync(staging, path); }
      catch (err) {
        if ((err as NodeJS.ErrnoException).code !== 'EEXIST') throw err;
        if (!readFileSync(path).equals(Buffer.from(media.bytes))) throw new Error('DM attachment content mismatch');
      }
    } finally { try { unlinkSync(staging); } catch { /* already absent */ } }
    return path;
  } catch (err) {
    onError?.(err);
    return null;
  }
}

/**
 * The one line in the inbound loop: decrypt the image + save it, returning the
 * local path (null for no image / could not be opened / could not be written).
 *
 * The three inbound loops (`index.ts` plugin, `main.ts` dev daemon, `mcp.ts` MCP
 * bridge) share this one — three isomorphic hand copies would eventually drift.
 * **Never throws**: an image should never be able to block text delivery.
 */
export function receiveDmMedia(
  dm: popclaw.event.IDirectMessage,
  recipient: Signer,
  dir: string,
  ts: number,
  warn: (m: string) => void,
  /** Used for naming (see dmMediaFileName). Omit = sigil only. */
  naming?: { sigilOf: (id: string) => string; nameOf?: (id: string) => string },
): string | null {
  const who = (dm.fromPopclawId ?? '').slice(0, 8);
  const media = readDmMedia(dm, recipient, (reason) =>
    warn(`popclaw: inbox — could not open the DM attachment (from ${who}…, ${reason}) — text delivered as usual`),
  );
  if (!media) return null;
  return saveDmMedia(
    dir,
    { ts, fromPopclawId: dm.fromPopclawId ?? '' },
    media,
    (err) => warn(`popclaw: inbox — failed to write attachment (from ${who}…): ${String(err)} — text delivered as usual`),
    naming ?? { sigilOf: deriveSigil },
  );
}

/** Read a stored attachment only within this root; never an arbitrary tool-supplied path. */
export function loadReceivedDmAttachment(storedPath: string, mediaDir: string): { path: string; image?: { data: string; mimeType: string } } {
  const file = realpathSync(storedPath);
  const rel = relative(realpathSync(mediaDir), file);
  if (rel.startsWith('..') || isAbsolute(rel) || !rel) throw new Error('Attachment is outside this inbox');
  const mimeType = ({ '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp', '.gif': 'image/gif' } as Record<string, string>)[extname(file).toLowerCase()];
  return { path: file, ...(mimeType ? { image: { data: readFileSync(file).toString('base64'), mimeType } } : {}) };
}
