// Regenerated proto namespaces are written to ./generated by `just gen-proto`.
// pbjs `-t static-module -w es6` output already exports `popclaw` as a named
// export. Re-export it directly — no additional namespacing.
//
// Consumers import like: `import { popclaw } from '@popclaw/contracts';`

export * from './generated/index.js';
export * from './house-session.js';
