import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  SUPPORTED_NODE_LINES,
  SUPPORTED_NODE_TEXT,
  parseNodeVersion,
  unsupportedNodeReason,
} from '../../../src/runtime/node-support.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, '../../../package.json');
const ROOT = resolve(HERE, '../../../../..');
const CI = resolve(ROOT, '.github/workflows/ci.yml');
/** The exporter that GENERATES the public repo's ci.yml, and so carries a
 *  second copy of the same pin. It is private-repo-only — it is not in its own
 *  INCLUDE_PATHS — so the exported tree has nothing to check here. */
const EXPORTER = resolve(ROOT, 'docs/release-review/export-popclaw-public.sh');
/** The image the server end runs. Private-repo-only for the same reason: the
 *  public repo ships the plugin, not our deployment. */
const DOCKERFILE = resolve(ROOT, 'deploy/Dockerfile.node-stack');
const SERVER_PKGS = ['apps/popclaw-canvas', 'apps/popclaw-web'].map((d) =>
  resolve(ROOT, d, 'package.json'),
);

/** The floor of the lowest supported line, which is what a CI pin must be:
 *  testing the OLDEST version we promise is the entire point of pinning. */
const FLOOR = [...SUPPORTED_NODE_LINES].sort((a, b) => a[0] - b[0])[0]!.join('.');
const pinIn = (file: string): string | null =>
  /^\s*NODE_VERSION:\s*"([^"]+)"/m.exec(readFileSync(file, 'utf8'))?.[1] ?? null;

describe('node-support', () => {
  // Single source of truth: runtime uses this table, npm uses engines, and both must describe the same contract.
  // Changing one without the other must fail this test, rather than emerge as a strange failure on someone's machine.
  it('和 package.json 的 engines.node 逐字一致', () => {
    const engines = JSON.parse(readFileSync(PKG, 'utf8')).engines.node as string;
    expect(SUPPORTED_NODE_TEXT).toBe(engines);
    // Beyond text, parse and compare the ranges too, preventing correct wording with an incorrect table.
    const fromText = engines
      .split('||')
      .map((s) => /(\d+)\.(\d+)\.(\d+)/.exec(s)!)
      .map((m) => [Number(m[1]), Number(m[2]), Number(m[3])]);
    expect(SUPPORTED_NODE_LINES.map((l) => [...l])).toEqual(fromText);
  });

  // CI is the third declaration. The first two were already tied by this test, but ci.yml was not. When the floor rose on 2026-09-17,
  // CI was missed and kept running on a version the plugin refused to start on, even while passing the
  // "22.22.3 is unsupported" assertion below. Drift was silent because nobody linked the declarations.
  // skipIf shares the export-script test's reason: public ci.yml is generated during export. The actual exported tree contains
  // that file and runs this test; only an intermediate candidate assembled by manual transplantation lacks it.
  it.skipIf(!existsSync(CI))('CI 钉的版本 = 最低受支持线的下限', () => {
    const pin = pinIn(CI);
    expect(pin).not.toBeNull();
    expect(unsupportedNodeReason(`v${pin}`)).toBeNull();
    expect(pin).toBe(FLOOR);
  });

  // Public ci.yml is generated by the export script's heredoc, not copied, and contains another
  // copy of the same pin. Updating only .github/ would still create a public repository on a Node version
  // forbidden by its own package.json: the first version external contributors see.
  it.skipIf(!existsSync(EXPORTER))('导出脚本里那份 pin 与 CI 逐字相同', () => {
    expect(pinIn(EXPORTER)).toBe(pinIn(CI));
  });

  // Third declaration: the server. canvas / web run only in our own image, so their engines follow
  // that FROM line, not the plugin contract. Distinct Node lines are intentional (CLAUDE.md,
  // unconventional-design point 6). On 2026-09-19 this was reversed: all six packages used the plugin
  // contract, making canvas/web require a Node version absent from their deployment.
  // Declarations ahead of runtime misrepresent the repository; pnpm does not enforce engines, so installation does not reveal it.
  it.skipIf(!existsSync(DOCKERFILE))('服务端包的 engines 跟着镜像那一行走', () => {
    const from = /^FROM node:([0-9]+)[.-]/m.exec(readFileSync(DOCKERFILE, 'utf8'))?.[1];
    expect(from).toBeDefined();
    for (const pkg of SERVER_PKGS) {
      const declared = (JSON.parse(readFileSync(pkg, 'utf8')) as { engines?: { node?: string } }).engines?.node;
      expect(declared, pkg).toBeDefined();
      // Every declared line must be supplied by the image. Moving its FROM line must fail this test.
      for (const line of declared!.split('||')) {
        expect(/(\d+)\./.exec(line)![1], `${pkg} declares a line the image does not provide`).toBe(from);
      }
    }
  });

  it('低于本线下限 → 报出来（22.19 就是 issue #332 那台）', () => {
    expect(unsupportedNodeReason('v24.15.9')).toContain('below the supported floor');
    expect(unsupportedNodeReason('v26.0.9')).toContain('below the supported floor');
  });

  it('线上不支持的大版本 → 报出来', () => {
    expect(unsupportedNodeReason('v25.9.0')).toContain('not a supported line');
    expect(unsupportedNodeReason('v22.22.3')).toContain('not a supported line');
  });

  it('支持的版本 → null（含各线下限那一版本身）', () => {
    for (const v of ['v24.16.0', 'v24.19.0', 'v26.1.0', 'v26.8.2']) {
      expect(unsupportedNodeReason(v)).toBeNull();
    }
  });

  it('解不出版本就别拦（绝不因为自己的正则挡住启动）', () => {
    expect(parseNodeVersion('not-a-version')).toBeNull();
    expect(unsupportedNodeReason('not-a-version')).toBeNull();
  });
});
